### PR TITLE
feat: Add authentication with personal access token

### LINKED ISSUE #46: Plugin broken due to authentication change (API Key deprecated by Gandi)
Hello,
This plugin is currently broken as it uses the deprecated authentication scheme with with the API Key, according to the [official documentation](https://api.gandi.net/docs/authentication/).

In order to fix that, the "_headers" function must be modified as follows (replace Apikey with Bearer):
```
def _headers(cfg):
    return {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + cfg.api_key
    }
```

### PR DESCRIPTION
**Pull request by cogk**
Closes #46

### CODE REVIEW

**Review by Themimitoof — APPROVED** [review]
Thanks @cogk for keeping the support of API Keys!

LGTM :+1:

**Comment by DorianCoding** [comment]
Hello and thanks a lot for those changes that allows us to change our configuration. If everyone is interested, you can do @Themimitoof changes in `/usr/lib/python3/dist-packages/certbot_plugin_gandi/gandi_api.py`.
When can we hope those changes to be pushed in apt and pip?

**Comment by obynio** [comment]
Hello, late review here but everything looks fine to me. I merged the PR, and updated the package on PyPI.
Unfortunately PyPI deprecated PGP key support so releases won't be signed with PGP anymore from now on.

https://pypi.org/project/certbot-plugin-gandi/1.5.0/

**Comment by DorianCoding** [comment]
Great! Thanks a lot for that.
For anyone using the apt version, the patch is blocked in sid due to Debian rules which is quite unfortunate. I'II try to get in touch with the apt maintainers or Debian to allo the patch to go through stable.
But as of today you need to do the modification manually from Github files.
If you use pip or Github files you should be fine now 👍

**Pull request merged**
