### PR TITLE
contrib: add systemd weekly timer/service for DNS renewal

### PR DESCRIPTION
**Pull request by jtheoof**
@obynio as I was about to write my own PKGBUILD for that I realized it could more benefitial for the community to have it in the repo.

I can update the PKGBUILD of the [AUR](https://aur.archlinux.org/packages/certbot-dns-gandi-git/) once this merged.

Thank you for reviewing this.

### CODE REVIEW

**Comment by jtheoof** [comment]
Did you have a chance to review this yet @obynio ? Do these files deserve their place in this repo ?

**Comment by obynio** [comment]
Sorry mate, I forgot about this pull request. Great initiative, feels like a good idea. I use Arch btw :upside_down_face:

**Comment by obynio** [comment]
Bumped version to 1.2.2

**Comment by jtheoof** [comment]
Awesome thanks !

**Pull request merged**
