### PR TITLE
Fixes https://github.com/obynio/certbot-plugin-gandi/issues/38

### LINKED ISSUE #38: Getting logger.warning on 3rd party plugins prefixes despite not using them
I am getting the warning that I see in the code:

> logger.warning("Certbot is moving to remove 3rd party plugins prefixes. Please use --authenticator dns-gandi --dns-gandi-credentials")

[`certbot plugins`](https://github.com/certbot/certbot/blob/a8015fa102bb8482e350a78ff3c50bbee5d27e37/certbot/certbot/_internal/main.py#L1142) gives:
```
2022-11-10 08:59:48,203:DEBUG:certbot._internal.log:Root logging level set at 30
2022-11-10 08:59:48,205:DEBUG:certbot._internal.main:Expected interfaces: None
2022-11-10 08:59:48,206:DEBUG:certbot._internal.main:Filtered plugins: PluginsRegistry(PluginEntryPoint#dns,PluginEntryPoint#dns-gandi,PluginEntryPoint#dns-ovh,PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2022-11-10 08:59:48,208:DEBUG:certbot._internal.display.obj:Notifying user: * dns
Description: Obtain certificates using a DNS TXT record (if you are using Gandi
for DNS).
Interfaces: Authenticator, Plugin
Entry point: dns = certbot_plugin_gandi.main:Authenticator

* dns-gandi
Description: Obtain certificates using a DNS TXT record (if you are using Gandi
for DNS).
Interfaces: Authenticator, Plugin
Entry point: dns-gandi = certbot_plugin_gandi.main:Authenticator

* dns-ovh
Description: Obtain certificates using a DNS TXT record (if you are using OVH
for DNS).
Interfaces: Authenticator, Plugin
Entry point: dns-ovh = certbot_dns_ovh._internal.dns_ovh:Authenticator

* nginx
Description: Nginx Web Server plugin
Interfaces: Installer, Authenticator, Plugin
Entry point: nginx = certbot_nginx._internal.configurator:NginxConfigurator

* standalone
Description: Spin up a temporary webserver
Interfaces: Authenticator, Plugin
Entry point: standalone = certbot._internal.plugins.standalone:Authenticator

* webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
```

but with some `certbot certonly --force-renew -d example.com`, [I am getting](https://github.com/certbot/certbot/blob/8066f230f57034429d83a718ed234b332bdfd597/certbot/certbot/_internal/main.py#L1687):

```
2022-11-10 09:52:22,879:DEBUG:certbot._internal.main:certbot version: 1.31.0
2022-11-10 09:52:22,880:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/bin/certbot
2022-11-10 09:52:22,880:DEBUG:certbot._internal.main:Arguments: ['--force-renew', '-d', 'degramont.fr']
2022-11-10 09:52:22,880:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#certbot-plugin-gandi:dns,PluginEntryPoint#certbot-plugin-gandi:dns-gandi,PluginEntryPoint#dns,PluginEntryPoint#dns-gandi,PluginEntryPoint#dns-ovh,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2022-11-10 09:52:28,403:DEBUG:certbot._internal.log:Root logging level set at 30
2022-11-10 09:52:28,406:DEBUG:certbot._internal.plugins.selection:Requested authenticator None and installer None
2022-11-10 09:52:28,420:WARNING:certbot_plugin_gandi.main:Certbot is moving to remove 3rd party plugins prefixes. Please use --authenticator dns-gandi --dns-gandi-credentials
```

I get the warning from certbot with the line:

> plugins = plugins_disco.PluginsRegistry.find_all()

Not getting the warning with the `certbot plugins` command and the line:

> filtered = plugins.visible().ifaces(ifaces)

### PR DESCRIPTION
**Pull request by HLFH**
Fixes https://github.com/obynio/certbot-plugin-gandi/issues/38

cc @obynio

### CODE REVIEW

**Comment by HLFH** [comment]
It has now been a long time that this deprecation has happened.
The warning was displayed even when the old way was not used, and only because the old dns entry_point was still supported by your plugin.
It would be great to remove this entry_point.
The README is sufficient by itself and explains well the configuration file migration.

**Comment by HLFH** [comment]
If you agree with these commits @obynio, when this PR is merged, could you please release version 1.4.1.

**Comment by obynio** [comment]
Ah yes, if I remember correctly we added this as a way to ensure retro compatibility with previous versions of cerbot. But it can be removed now. These changes are fine.

**Comment by obynio** [comment]
It's merged and released on PyPI with version 1.4.1

**Comment by HLFH** [comment]
@obynio Thank you!

**Pull request merged**
